<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 static/models/character.glb
-->

<script lang="ts">
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'
	import { onDestroy } from 'svelte';
	import { buttonIdle, buttonRun, buttonWalk } from '$lib/character_state';

  export const ref = new Group()

  const gltf = useGltf('models/character.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  console.log(gltf)

  let currentActionKey = 'idle'

  console.log(Object.entries($actions))

  $: $actions[currentActionKey]?.play()

const unsub1 = buttonIdle.subscribe(() => {
  console.log('transition to idle')
  transitionTo('idle', 0.3)
})

const unsub2 = buttonWalk.subscribe(() => {
  console.log('transition to run')
  transitionTo('CharacterArmature|Run', 0.3)
})

const unsub3 = buttonRun.subscribe(() => {
  console.log('transition to run')
  transitionTo('run', 0.3)
})

function transitionTo(nextActionKey: string, duration = 1) {
 
  const currentAction = $actions[currentActionKey]
  const nextAction = $actions[nextActionKey]
  console.log(actions)
  if (!nextAction || currentAction === nextAction) return
  // Function inspired by: https://github.com/mrdoob/three.js/blob/master/examples/webgl_animation_skinning_blending.html
  nextAction.enabled = true
  if (currentAction) {
    currentAction.crossFadeTo(nextAction, duration, true)
  }
  // Not sure why I need this but the source code does not // TODO HAHAHAHA
  nextAction.play()
  currentActionKey = nextActionKey
}

onDestroy(() => {
  // We unsubscribe otherwise we'd have old subscriptions still active
  unsub1()
  unsub2()
  unsub3()
})


  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Root_Scene">
      <T.Group name="RootNode">
        <T.Group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <T is={gltf.nodes.Root} />
        </T.Group>
        <T.Group name="Medieval_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <T.SkinnedMesh
            name="Medieval_Body_1"
            geometry={gltf.nodes.Medieval_Body_1.geometry}
            material={gltf.materials.Black}
            skeleton={gltf.nodes.Medieval_Body_1.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Body_2"
            geometry={gltf.nodes.Medieval_Body_2.geometry}
            material={gltf.materials.LightBrown}
            skeleton={gltf.nodes.Medieval_Body_2.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Body_3"
            geometry={gltf.nodes.Medieval_Body_3.geometry}
            material={gltf.materials.DarkBrown}
            skeleton={gltf.nodes.Medieval_Body_3.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Body_4"
            geometry={gltf.nodes.Medieval_Body_4.geometry}
            material={gltf.materials.Skin}
            skeleton={gltf.nodes.Medieval_Body_4.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Body_5"
            geometry={gltf.nodes.Medieval_Body_5.geometry}
            material={gltf.materials.Gold}
            skeleton={gltf.nodes.Medieval_Body_5.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Body_6"
            geometry={gltf.nodes.Medieval_Body_6.geometry}
            material={gltf.materials.Metal}
            skeleton={gltf.nodes.Medieval_Body_6.skeleton}
          />
        </T.Group>
        <T.Group name="Medieval_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <T.SkinnedMesh
            name="Medieval_Feet_1"
            geometry={gltf.nodes.Medieval_Feet_1.geometry}
            material={gltf.materials.LightBrown}
            skeleton={gltf.nodes.Medieval_Feet_1.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Feet_2"
            geometry={gltf.nodes.Medieval_Feet_2.geometry}
            material={gltf.materials.DarkBrown}
            skeleton={gltf.nodes.Medieval_Feet_2.skeleton}
          />
        </T.Group>
        <T.Group name="Medieval_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <T.SkinnedMesh
            name="Medieval_Head_1"
            geometry={gltf.nodes.Medieval_Head_1.geometry}
            material={gltf.materials.Black}
            skeleton={gltf.nodes.Medieval_Head_1.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Head_2"
            geometry={gltf.nodes.Medieval_Head_2.geometry}
            material={gltf.materials.DarkBrown}
            skeleton={gltf.nodes.Medieval_Head_2.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Head_3"
            geometry={gltf.nodes.Medieval_Head_3.geometry}
            material={gltf.materials.Skin}
            skeleton={gltf.nodes.Medieval_Head_3.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Head_4"
            geometry={gltf.nodes.Medieval_Head_4.geometry}
            material={gltf.materials.White}
            skeleton={gltf.nodes.Medieval_Head_4.skeleton}
          />
          <T.SkinnedMesh
            name="Medieval_Head_5"
            geometry={gltf.nodes.Medieval_Head_5.geometry}
            material={gltf.materials.Brown}
            skeleton={gltf.nodes.Medieval_Head_5.skeleton}
          />
        </T.Group>
        <T.SkinnedMesh
          name="Medieval_Legs"
          geometry={gltf.nodes.Medieval_Legs.geometry}
          material={gltf.materials.Black}
          skeleton={gltf.nodes.Medieval_Legs.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
